---
deployment:
  tasks:
    - export DEPLOYPATH=/home/socially/public_html/
    - /bin/cp -R translations $DEPLOYPATH
    - /bin/cp -R var $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R bin $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R migrations $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp docker-compose.override.yml $DEPLOYPATH
    - /bin/cp docker-compose.yml $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp symfony.lock $DEPLOYPATH
    - /bin/cp webpack.config.js $DEPLOYPATH
