controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_home_page:
    path: /Home
    controller: App\Controller\HomeController::mainpage
